### ISSUE TITLE
Equidistant Gene Position in Synteny Diagrams

### ISSUE THREAD

**Issue by RohanNathHERE** [nvelden/geneviewer#10]
Thank you for developing such a useful package! I am currently using a script to plot synteny diagrams with coordinates and gene names and connect them based on the same name. The script works well for the most part, but I've encountered an issue where some genes are too large and others are too small, which affects the quality and clarity of the figures. I would like to make the genes equidistant from each other in the plot.

**Current script**
`
#Create the main GC_chart with various components
main_chart <- GC_chart(data2, 
                       cluster = "cluster", 
                       group = "name", 
                       height = "300px") %>%
  GC_title(title = "Synteny", height = "30px") %>%
  GC_labels(label = "name", 
            cluster = "Homo_sapiens", 
            itemStyle = list(list(index = 5, fill = "red", fontWeight = "bold"))) %>%
  GC_labels(label = "name", 
            cluster = 2, 
            itemStyle = list(list(index = 5, fill = "red", fontWeight = "bold"))) %>%
  GC_genes(show = TRUE, 
           stroke = "black", 
           strokeWidth = 1, 
           marker = "rbox", 
           marker_size = "small") %>%
  GC_color(colorScheme = "schemeAccent") %>%
  GC_legend()

#Enhance the main_chart with additional components and create cluster_plot
cluster_plot <- main_chart %>%
  GC_links("name") %>%
  GC_genes(show = TRUE, 
           stroke = "black", 
           strokeWidth = 1, 
           marker = "rbox", 
           marker_size = "small") %>%
  GC_labels(label = "name", 
            itemStyle = list(list(index = 5, fill = "red", fontWeight = "bold"))) %>%
  GC_labels(label = "name", 
            cluster = 2, 
            itemStyle = list(list(index = 5, fill = "red", fontWeight = "bold"))) %>%
  GC_legend(TRUE) %>%
  GC_color(colorScheme = "schemePaired")
`
**Desired Feature**
I would like to add functionality to the script that ensures genes are equidistant from each other in the plot. This would improve the visual quality and clarity of the synteny diagrams. Just like this:
[output.pdf](https://github.com/user-attachments/files/16402452/output.pdf)

Thank you for your assistance!

**Comment by nvelden** [comment]
I added a function `GC_normalize` that I think is able to do what you want. Have a look at the documentation [here](https://nvelden.github.io/geneviewer/articles/geneviewer.html#gene-normalization).

**Comment by RohanNathHERE** [comment]
Hello! Thank you for your response. The `GC_normalize` script is working perfectly, but I'm encountering a new issue with the `GC_coordinates` and `GC_scale` commands. These scripts use gene coordinates to label genes and scales, but many of my gene coordinates are extremely large, (e.g., `87472973`, `87512335`, etc.), causing the image labels to appear disordered. Is there a function within these scripts that can help convert these coordinates to `KB` or `MB`?

This is my script:

`
main_chart <- GC_chart(data, 
                       cluster = "cluster", 
                       group = "name", 
                       height = "300px") %>%
  GC_normalize(group = "name", 
               gap = 0.01, 
               preserve_gene_length = FALSE) %>%
  GC_tooltip(cluster = 1, 
             formatter = "<b>Start:</b> {original_start}<br><b>End:</b> {original_end}") %>%
  GC_title(title = "Synteny", 
           height = "30px") %>%
  GC_coordinates(FALSE,
    rotate = -45,
    yPositionTop = 55,
    yPositionBottom = 45,
    overlapThreshold = 20,
    tickStyle = list(stroke = "grey", strokeWidth = 1, lineLength = 10),
    textStyle = list(fill = "gray", fontSize = "10px", fontFamily = "Arial", cursor = "default"),
    fontSize = "6px"
  ) %>%
  GC_scale(ticksCount = 10) %>%
  GC_labels(label = "name", 
            itemStyle = list(list(index = 5, 
                                  fill = "red", 
                                  fontWeight = "bold"))) %>%
  GC_genes(show = TRUE, 
           stroke = "black", 
           strokeWidth = 1, 
           marker = "rbox", 
           marker_size = "small") %>%
  GC_color(colorScheme = "schemeAccent") %>%
  GC_legend(FALSE)

#Enhance the main_chart with additional components and create the cluster plot
cluster_plot <- main_chart %>%
  GC_links("name") %>%
  GC_color(colorScheme = "schemePaired")  # Only change the color scheme
`

Thank you again for your assistance!

**Comment by nvelden** [comment]
I have updated the package to include a `ticksFormat`option in both the `GC_coordinates` and `GC_scale` functions. For your case you could for instance use format ".2s". For other formats see: [D3-formats](https://d3js.org/d3-format) 

```
GC_chart(ophA_clusters, group = "class", cluster = "cluster", height = "150px") %>%
    GC_scale(
        ticksFormat = ".2s", # Default: ",.0f"
    ) %>%
    GC_legend(FALSE)
```

**Comment by RohanNathHERE** [comment]
That works perfectly for `GC_scale`; however, when I include `ticksFormat = ".2s"` for `GC_coordinates`, it doesn't seem to work and prints the entire coordinate. Is it working for you? This is my script:

```r
main_chart <- GC_chart(data, 
                       cluster = "cluster", 
                       group = "name", 
                       height = "300px") %>%
  GC_normalize(group = "name", 
               gap = 0.01, 
               preserve_gene_length = FALSE) %>%
  GC_tooltip(cluster = 1, 
             formatter = "<b>Start:</b> {original_start}<br><b>End:</b> {original_end}") %>%
  GC_title(title = "Synteny", 
           height = "30px") %>%
  GC_coordinates(
    rotate = -45,
    ticksFormat = ".2s",
    yPositionTop = 55,
    yPositionBottom = 45, 
    overlapThreshold = 20,
    tickStyle = list(stroke = "grey", strokeWidth = 1, lineLength = 10),
    textStyle = list(fill = "gray", fontSize = "10px", fontFamily = "Arial", cursor = "default"),
    fontSize = "6px"
  ) %>%
  GC_scale(ticksFormat = ".2s", ticksCount = 10) %>%
  GC_labels(label = "name", 
            itemStyle = list(list(index = 5, 
                                  fill = "black", 
                                  fontWeight = "bold"))) %>%
  GC_genes(show = TRUE, 
           stroke = "black", 
           strokeWidth = 1, 
           marker = "rbox", 
           marker_size = "small") %>%
  GC_legend(FALSE)

# Enhance the main_chart with additional components and create the cluster plot
cluster_plot <- main_chart %>%
  GC_links("name",
           use_group_colors = TRUE) %>%
  GC_color(colorScheme = "schemePaired")
``` 

As always, thank you for your response!

**Comment by nvelden** [comment]
I just pushed an update that includes the `ticksFormat` option in the `GC_coordinates` function. Could you download the latest version from github?

I could reproduce you issue with the misaligned links when rendering to PDF. I could solve it if I set an explicit `width` for the graph. Does this work for you?

`GC_chart(data, cluster = "cluster", group = "name", width = "800px", height = "300px")`

**Comment by RohanNathHERE** [comment]
I’ve managed to resolve the issue with `width` by setting `width = 800px`, which improved the clarity of my plots. Now, I need to adjust the width of the linkers to enhance clarity even further. How do I do it? Additionally, I’m having trouble finding the source code for the linker function. Could you provide the source code or guide me on where to locate it?

**Comment by nvelden** [comment]
I have just now added an option to set the `linkWidth` in the `GC_links()` function:

```
  GC_chart(
    ophA_clusters,
    cluster = "cluster",
    group = "class",
    height = "300px"
  ) %>%
  GC_links(
    "class",
    use_group_colors = TRUE,
    curve = TRUE,
    label = FALSE,
    linkWidth = 0.1,
  )
```
The source code is in the R folder under geneviewer.R. The code to generate the graph elements is under inst/htmlwidgets/geneviewer-0.1.8

**Comment by RohanNathHERE** [comment]
Thank you; this is very helpful. I'm closing the issue for now, and I'll reach out if I run into any more problems.
