### ISSUE TITLE
Error in GC_links

### ISSUE THREAD

**Issue by shengqiangJ** [nvelden/geneviewer#2]
I ran the code using the sample file and was able to generate gene track graphics, but it did not connect the genes. NO error generated. Is there a solution?    

here is my code:

BlastP_results_functions <- left_join(BlastP_results, BGC0000055_info, by = dplyr::join_by(BlastP == protein_id ) )
GC_chart(
  data = BlastP_results_functions,
  cluster = "cluster",
  group = "Functions",
  strand = "strand",
  height = "600px"
) %>%
  GC_labels(label = "Gene", cluster = 1) %>% 
  GC_links(group = "BlastP",  identity = TRUE,show_links = TRUE) %>%  
  GC_clusterLabel() %>%
  GC_legend(TRUE)

**Comment by nvelden** [comment]
Did you try with the latest version on Github? I am still actively developing the package so older versions might not work anymore for some of the tutorials.
