### ISSUE TITLE
Having problem with import some specific .gbk files

### ISSUE THREAD

**Issue by yamn29302** [nvelden/geneviewer#3]
Hi,

Thanks for developing this sweet package saving me lots of time playing with powerpoint.
I have encountered a problem with some specific .gbk files downloaded directly from GenBank.
More specifically, it has something to do with read_gbk() function.
Most of the files I have can be transformed into df perfectly. 
However I've got 2 files can't be parsed by read_gbk() as expected.
The "FEATURES" of the resulting list is somehow going wrong which I can't fix.
![螢幕擷取畫面 2024-04-20 141412](https://github.com/nvelden/geneviewer/assets/30976993/94ff1cd7-f9b7-4056-a84f-f3df9b73dd57)

The .gbk files are uploaded onto google drive. The link is provided below.
[https://drive.google.com/drive/folders/1CRT8u6T_U8YflGqzbC5uwfq7dVfKBtyt?usp=drive_link](url)

**Comment by nvelden** [comment]
The supplied GenBank files contain genomic data for multiple loci, each separated by "//" and with its own FEATURES section. The function will only read the FEATURES from the first locus. To access all information, either split each locus into a separate GenBank file or identify and load only the locus containing your gene of interest.

**Comment by yamn29302** [comment]
Many thanks to your reply!!
The finction works perfectly after I split the .gbk file into mutiple files.
The splitting script I used is below. (change .txt to .sh and worked under linux environment)
[split.txt](https://github.com/nvelden/geneviewer/files/15066178/split.txt)
