### ISSUE TITLE
Request for feature to save as picture (svg, png) directly from the R package

### ISSUE THREAD

**Issue by jonng2024** [nvelden/geneviewer#4]
Hi, thanks for developing this library, its a lifesaver for me! Would it be possible to give us the ability to save the chart directly as svg and png please? 

If we choose the png option, would it be possible to specify the resolution? This is because I realised that for reasonably complex plots, the resolution is not good enough when I zoom in to look at genes.

Perhaps this library could be connected to ggplot somehow? Thank you =)

**Comment by nvelden** [comment]
I am working on a better solution but for now you will need to use `webshot2` to save the plots like explained [here](https://nvelden.github.io/geneviewer/articles/geneviewer.html#saving-plots). If you need higher quality images you can increase the zoom.

```
library(webshot2)

# Generate plot with width and height specifications
cluster_plot <- 
  GC_chart(ophA_clusters, 
           group = "class", 
           cluster = "cluster",
           width = "400px",
           height = "250px")

# Save plot to temp.html file
htmlwidgets::saveWidget(cluster_plot, "temp.html", selfcontained = TRUE)

# Save plot to .png (or .jpg, .jpeg, .webp, .pdf)
webshot2::webshot(
  "temp.html", 
  "output.png", 
  zoom = 2, # Increase zoom for higher resolution
  selector = ".geneviewer")
```

**Comment by jonng2024** [comment]
Ok sure, thank you so much for all your hard work =)

**Comment by zuzanahalenkova** [comment]
Hi, I have a related issue - is there a way to export the pictures including the links between clusters? The links get lost after exporting to html. I have noticed that they are also missing in the examples at https://nvelden.github.io/geneviewer/reference/GC_links.html.
Thank you for this great library!

**Comment by nvelden** [comment]
What browser are you using? I can see the links on Chrome and Firefox.

**Comment by zuzanahalenkova** [comment]
Just tried using Chrome and it works, thank you for the tip and for the quick response! :)

**Comment by nvelden** [comment]
There was an issue the way the links were rendering. They should now also be visible in Firefox. Thanks a lot for pointing this out!

**Comment by Dx-wmc** [comment]
Hi, can it directly support traditional saving methods, such as ggsave? For now, the experience of webshot2 is too bad, I cannot output the size correctly, and the exported PDF is not vectorized and cannot be further modified.

**Comment by nvelden** [comment]
Unfortunately, `ggsave` cannot be used to save these plots because the package is not built on `ggplot2`. However, using the below code I am able to set the exact dimensions and when exported to .pdf, it will be vectorized.

```
cluster_plot <- 
  GC_chart(ophA_clusters, 
           group = "class", 
           cluster = "cluster",
           width = "400px", # Essential to prevent misalignment of gene links
           height = "250px")

# Save plot to temp.html file
htmlwidgets::saveWidget(cluster_plot, "temp.html", selfcontained = TRUE)

# Save plot to .png (or .jpg, .jpeg, .webp, .pdf)
webshot2::webshot(
  "temp.html", 
  "output.png", 
  zoom = 1, # Increase zoom for higher resolution
  selector = ".geneviewer")

```

**Comment by Dx-wmc** [comment]
Thanks to your code, I was able to set the dimensions correctly. However, I noticed a problem with the display of gene names. For example, when the gene name is estX, ggplot renders it as a single unit, but in geneviewer, each letter appears separately, making it difficult to modify. Strangely, the track numbers are displayed as a whole. I wonder if this difference requires an additional setting to fix. Could you please help me resolve this issue?

**Comment by nvelden** [comment]
`geneviewer` is rendering the labels as single text but it looks like `webshot2` is splitting the labels to single characters when converting from  .html to .pdf. What you could do is changing the labels within the output.html file (using the browser developer tools). Save the changes and then converting to .pdf. 

<img width="1123" alt="Image" src="https://github.com/user-attachments/assets/de62338e-88f7-47e4-8cc2-77b040ff748c" />
