### ISSUE TITLE
Partial Product Names for Proteins Containing "/"

### ISSUE THREAD

**Issue by ceaton1191** [nvelden/geneviewer#9]
the gbk_features_to_df() function returns protein names up to the "/" character for proteins with a / in their name. For example, I'm interested in the _Candida auris_ gene CJJ07_001621, which is classified as a calcium/proton exchanger in my genbank file. However, if I create a CDS dataframe using this function and query it for the locus ID "CJJ07_001621", it returns the product "calcium" instead of "calcium/proton exchanger." This seems to mainly be a common problem for ion pumps.

**Comment by nvelden** [comment]
Could you give it another try? I just pushed a change that hopefully fixes this issue.

**Comment by ceaton1191** [comment]
It's fixed! Thanks
